"""Build versioned object store tests"""


def scons():
    """Execute build"""
    Import('env')

    # build d_vector unit test
    venv = env.Clone()

    venv.Append(OBJPREFIX="dlck_d_vector_ut_")
    venv.require('cmocka', 'pmdk')

    libraries = ['cmocka', 'gurt', 'daos_common_pmem']

    dlck_d_vector_ut_src = ['dlck_d_vector_ut.c']

    dlck_d_vector_ut = venv.d_test_program('dlck_d_vector_ut', dlck_d_vector_ut_src, LIBS=libraries)
    venv.Install('$PREFIX/bin/', dlck_d_vector_ut)

    # build and install the test helper
    henv = env.Clone()

    henv.Append(OBJPREFIX="dlck_ut_helper_")
    henv.Append(CPPPATH=[Dir('../../../').srcnode()])
    henv.AppendUnique(RPATH_FULL=['$PREFIX/lib64/daos_srv'])
    henv.require('argobots', 'cmocka')

    libraries = [
        'vos_srv', 'gurt', 'daos_common_pmem', 'bio', 'cmocka', 'uuid', 'dtx', 'abt', 'pthread'
    ]

    helper_src = [
        'dlck_test_helper.c',
        '../dlck_abt.c',
        '../dlck_tls.c',
        '../dlck_args_engine.c',
        '../dlck_args_files.c',
        '../dlck_args_parse.c',
        '../dlck_engine.c',
        '../dlck_pool.c',
        '../../../dtx/tests/srv_mock.c',
        '../../../dtx/tests/ult_mock.c',
        '../../../dtx/tests/pl_map_mock.c',
        '../../../dtx/tests/sched_mock.c',
        '../../../engine/util.c',
        '../../../mgmt/srv_util_file.c',
    ]
    helper = henv.d_test_program('dlck_test_helper', helper_src, LIBS=libraries)
    henv.Install('$PREFIX/bin/', helper)


if __name__ == "SCons.Script":
    scons()
