"""Build versioned object store tests"""


def scons():
    """Execute build"""
    Import('env')

    tenv = env.Clone()

    tenv.Append(CPPPATH=[Dir('..').srcnode()])
    tenv.Append(CPPPATH=[Dir('../../../vos').srcnode()])
    tenv.Append(OBJPREFIX="dlck_ut_")
    tenv.Append(CPPDEFINES=['-DDAOS_PMEM_BUILD', '-DDLCK_ENABLED'])
    tenv.AppendUnique(RPATH_FULL=['$PREFIX/lib64/daos_srv'])

    tenv.AppendUnique(LINKFLAGS=['-Wl,--wrap=gc_init_cont'])

    libraries = ['uuid', 'bio', 'gurt', 'cmocka', 'daos_common_pmem', 'abt', 'vea']

    tenv.require('argobots')
    vos_src = Glob('../../../vos/*.c')
    dlck_ut_src = ['dlck_ut.c', 'vos_gc_mocks.c',
                   '../../../dtx/tests/sched_mock.c',
                   '../../../dtx/tests/srv_mock.c',
                   ]
    dlck_ut = tenv.d_test_program('dlck_ut', dlck_ut_src + vos_src, LIBS=libraries)
    tenv.Install('$PREFIX/bin/', dlck_ut)


if __name__ == "SCons.Script":
    scons()
