name: CI Experiment

on:
  workflow_dispatch:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/janekmi/daos:CI-experiment
    steps:
      - name: Hello world
        run: |
          sudo dnf install tree
          tree /opt/daos
