name: CI Experiment

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: daos-stack/daos
          path: daos
          ref: janekmi/local_tx2
      - name: Install dependencies
        working-directory: daos/utils/scripts
        run: sudo ./install-ubuntu.sh
      - name: Install builders
        run: |
          sudo apt-get install scons
          sudo pip3 install meson
      - name: Build
        working-directory: daos
        run: scons PREFIX=/opt/daos TARGET_TYPE=release --build-deps=yes -j32
