name: CI Experiment

on:
  workflow_dispatch:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/janekmi/daos:CI-experiment
    env:
      DEPS_JOBS: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
      - name: Build and install
        run: |
          scons --jobs "$DEPS_JOBS" PREFIX=/opt/daos COMPILER="$COMPILER" \
            BUILD_TYPE=debug TARGET_TYPE=release -c install
