name: CI Test

on:
  push:
    paths:
      - .github/workflows/ci_test.yml
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/janekmi/daos:CI-experiment
      options: --user root --privileged
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    steps:
      - name: debug
        run: |
          dnf install tree zstd

      - name: Restore /opt/daos cache
        uses: actions/cache/restore@v4
        with:
          key: install
          path: /opt/daos/*
          fail-on-cache-miss: true

      - name: Restore src cache
        uses: actions/cache/restore@v4
        with:
          key: src
          path: '*'
          fail-on-cache-miss: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: janekmi/daos
          ref: CI-experiment
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
          path: head
      
      - name: Patch source code
        run: |
          cp head/utils/node_local_test.py utils/node_local_test.py
          cp head/ci/docker_nlt.sh ci/docker_nlt.sh

      - name: Setting up daos_server_helper
        # shell: bash --noprofile --norc -e -x -o pipefail {0}
          # sudo --preserve-env=SL_PREFIX,SL_SPDK_PREFIX ./utils/setup_daos_server_helper.sh
        run: |
          . utils/sl/setup_local.sh
          ./utils/setup_daos_server_helper.sh
          rm /opt/daos/bin/daos_server_helper

      - name: Container copy test
        run: |
          ./utils/node_local_test.py --no-root --memcheck no \
            --system-ram-reserved 1 --test cont_copy
