name: Test

on:
  workflow_call:
    inputs:
      VARIABLE:
        type: string
        required: true

jobs:
  XXX:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.VARIABLE }}
